name: super_core
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/chdown/super_core

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ">=2.0.0"
  decimal: ">=2.3.3"
  dio: ">=5.0.0"
  intl: ">=0.18.0"
  lottie: ">=3.0.0"
