name: super_core
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/chdown/super_core

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ">=2.0.0 <5.0.0"
  rational: ">=2.0.0 <5.0.0"
  crypto: ">=3.0.0 <5.0.0"
  convert: ">=3.0.0 <5.0.0"
  dio: ^5.4.1
  logger: ^2.1.0
  connectivity_plus: ^5.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
